prefix: '.'
activity_name: 'Hennyano'
tweets_check_period: 10
tweets_updater_retry_delay: 300
tasks_monitor_check_period: 60
tasks_monitor_log_period: 14400
auto_turn_off_notification: true
auto_unfollow: true
use_fx: false
fx_image: true
default_message: |
  {mention}**{author}** just {action} here: 
  {url}