prefix: '.'
activity_name: '{count} accounts'
activity_type: 'watching'

tweets_check_period: 10
tweets_updater_retry_delay: 5
tasks_monitor_check_period: 1
tasks_monitor_log_period: 4

auto_change_client: false
auto_turn_off_notification: true
auto_unfollow: true

embed:
  type: 'built_in'

  built_in:
    fx_image: true
    video_link_button: false
    footer_logo: 'blue_bird'
    
  fx_twitter:
    original_url_button: false

default_message: |
  {mention}**{author}** just {action} here: 
  {url}